config/routes.rb
Crowdcloud::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resource :dashboard, controller: :dashboard do
    post :filter
  end

  namespace :admin do
    resources :comments do
      resources :reports
    end
    resources :spaceship_settings
    resources :heuristics
    resources :users do
      member do
        post :ban
        post :unban
        get :ban_ip
        post :ban_ip
        post :unban_ip
      end
    end
  end

  resource :comments do
    get :recent, on: :collection
  end

  resources :documents do
    get :search, :on => :collection
    post :quickfacet, :on => :collection
    post :toggle_visibility, :on => :collection
    post :watch, :on => :member
    post :unwatch, :on => :member
    resources :comments do
      member do
        post :vote_up
        post :vote_down
        post :flag
        post :flag_reason
        put :report
        post :toggle
      end
    end
    resources :questions
  end

  root :to => 'documents#index'

  match ':slug', :via => :get, :to => 'static_pages#show', :as => 'static_page'
  match ':slug', :via => :put, :to => 'static_pages#update', :as => 'static_page'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :set_body_class

  def show
    authorize! :view, :dashboard

    if params[:per_page] && params[:per_page].to_i <= 50
      current_user.update_attribute(:results_per_page, params[:per_page])
      redirect_to dashboard_path and return
    end

    @filters = current_user.stream_filters
    @page = (params[:page] || 1).to_i
    @per_page = current_user.results_per_page

    # TODO populate from filters
    @events = current_user.dashboard_events.page(@page).per(@per_page)

    documents = @events.select { |e| e.respond_to?(:document) }.collect(&:document) # not all events have document!
    @watched_documents = current_user.select_watched_documents(documents)
  end

  def filter
    filters = params[:filters] || {}
    current_user.stream_show_openings = filters[:show_openings] || false
    current_user.stream_show_watching = filters[:show_watching] || false
    current_user.stream_show_my_comments = filters[:show_my_comments] || false
    current_user.stream_show_other_comments = filters[:show_other_comments] || false
    current_user.stream_show_answers = filters[:show_answers] || false
    current_user.save!
    redirect_to dashboard_path
  end

  private
  def set_body_class
    @body_class = "detail"
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_watch.html.erb
<% if current_user %>
  <% if @watched_documents.include?(document) %>
    <% label = "Sledované" %>
    <% if @watched_documents.notice_for(document) %>
      <% title = @watched_documents.notice_for(document) %>
      <% css_class = "watched with_note" %>
    <% else %>
      <% title = "Odobrať zmluvu zo sledovaných zmlúv" %>
      <% css_class = "watched" %>
    <% end %>
  <% else %>
      <% title = "Pridať zmluvu medzi sledované zmluvy" %>
      <% css_class = "unwatched" %>
      <% label = "Sledovať" %>
  <% end %>

  <div class="<%= css_class %>" title="<%= title %>" data-watch-url="<%= watch_document_path(document) %>" data-unwatch-url="<%= unwatch_document_path(document) %>"><%= label %></div>
<% end %>

app/views/dashboard/show.html.erb
<div style="clear: both;"></div>
<h1 class="page-title">Moje zmluvy</h1>
<div id="content" class="dashboard">
  <div id="top">
    <div id="menu" class="glow">
      <h2>Posledné zmeny</h2>
      <%= form_tag filter_dashboard_path, class: 'dashboard' do %>
          <p><%= check_box_tag 'filters[show_openings]', 1, @filters[:show_openings] %><%= label_tag 'filters[show_openings]', 'Otvorenie sledovaných zmlúv' %></p>

          <p><%= check_box_tag 'filters[show_watching]', 1, @filters[:show_watching] %><%= label_tag 'filters[show_watching]', 'Sledovanie zmlúv' %></p>

          <p><%= check_box_tag 'filters[show_my_comments]', 1, @filters[:show_my_comments] %><%= label_tag 'filters[show_my_comments]', 'Moje komentáre' %></p>

          <p><%= check_box_tag 'filters[show_other_comments]', 1, @filters[:show_other_comments] %><%= label_tag 'filters[show_other_comments]', 'Cudzie komentáre' %></p>

          <p><%= check_box_tag 'filters[show_answers]', 1, @filters[:show_answers] %><%= label_tag 'filters[show_answers]', 'Zodpovedanie otázok' %></p>
      <% end %>
    </div>
    <div class="top-right glow">
      <div class="header">
        <h1>Zoznam posledných zmien</h1>
        <%= form_tag dashboard_path, class: :per_page, method: :get do %>
            <%= label_tag :per_page, 'Načítať po' %>
            <%= select_tag :per_page, options_for_select([['5 záznamoch', 5], ['10 záznamoch', 10], ['25 záznamoch', 25], ['50 záznamoch', 50]], @per_page) %>
        <% end %>
      </div>
      <div class="inner">
        <% if @events.any? %>
            <%
               grouped_events = []
               current_group = []
               current_aggregate = @events.first.aggregate_parent # TODO what if empty?
               @events.each do |event|
                 if current_aggregate == event.aggregate_parent
                   current_group << event
                 else
                   grouped_events << current_group
                   current_group = [event]
                   current_aggregate = event.aggregate_parent
                 end
               end
               grouped_events << current_group unless current_group.empty?
            %>
            <% grouped_events.each do |group| %>
                <div class="events-group">
                  <% first_event = group.first %>
                  <% if first_event.aggregate_parent %>
                      <%= render partial: "events/#{first_event.aggregate_parent_type}", object: first_event.aggregate_parent %>
                  <% end %>
                  <%= render partial: group, as: :event %>
                </div>
            <% end %>
        <% end %>
      </div>
      <% if @events.total_pages > @page %>
          <div class="footer">
            <p><%= link_to 'Zobraziť staršie záznamy', dashboard_path(page: @page + 1) %></p>
          </div>
      <% end %>
    </div>
    <div class="clear"></div>
  </div>
</div>