config/routes.rb
Crowdcloud::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resource :dashboard, controller: :dashboard do
    post :filter
  end

  namespace :admin do
    resources :comments do
      resources :reports
    end
    resources :spaceship_settings
    resources :heuristics
    resources :users do
      member do
        post :ban
        post :unban
        get :ban_ip
        post :ban_ip
        post :unban_ip
      end
    end
  end

  resource :comments do
    get :recent, on: :collection
  end

  resources :documents do
    get :search, :on => :collection
    post :quickfacet, :on => :collection
    post :toggle_visibility, :on => :collection
    post :watch, :on => :member
    post :unwatch, :on => :member
    resources :comments do
      member do
        post :vote_up
        post :vote_down
        post :flag
        post :flag_reason
        put :report
        post :toggle
      end
    end
    resources :questions
  end

  root :to => 'documents#index'

  match ':slug', :via => :get, :to => 'static_pages#show', :as => 'static_page'
  match ':slug', :via => :put, :to => 'static_pages#update', :as => 'static_page'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :user, :votes, :parent, :area, :document

  belongs_to :page
  belongs_to :user
  belongs_to :document
  belongs_to :censored_by, class_name: 'User'

  has_many :replies, :class_name => 'Comment', :foreign_key => :parent_id, :dependent => :destroy
  belongs_to :parent, :class_name => 'Comment'
  has_many :votings
  has_many :reports, :class_name => 'CommentReport', dependent: :destroy

  validates :comment, :presence => true

  scope :censored, where('censored_at IS NOT NULL')
  scope :uncensored, where(censored_at: nil)
  scope :reported, where('reports_count > 0')
  scope :chronologically, order('id DESC')
  scope :by_last_change, order('updated_at DESC')

  def author_label
    user.try(:label) || 'Anonym'
  end

  def related_to_document_area?
    area
  end

  def toggle(censor)
    update_column(:censored_at, censored? ? nil : DateTime.now)
    update_column(:censored_by_id, censor.id)
  end

  def censored?
    censored_at?
  end

  def replies_count
    replies.count
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController
  authorize_resource

  def index
    @latest = Comment.chronologically.limit(10)
    @comments = Comment.censored.by_last_change.page(params[:page])
    @reports = CommentReport.includes(:comment).order('id DESC').page(params[:page])
    @suspicious_comments = Comment.where('flags > 0').by_last_change.page(params[:page])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_document, except: :recent
  before_filter :find_comment, :except => [:create, :recent]

  def create
    if params[:area]
      attachment = @document.attachments.find_by_number(params[:attachment_number])
      page = attachment.pages.find_by_number(params[:page_number])
      @comment = page.comments.build(:comment => params[:comment], :area => params[:area].to_json, :user => current_user, :document => @document)
    else
      if params[:comment][:reply_to].empty?
        @comment = @document.comments.build(:comment => params[:comment][:comment], :user => current_user)
      else
        @comment = Comment.find(params[:comment][:reply_to])
        reply = @document.comments.build(:comment => params[:comment][:comment], :user => current_user, :parent => @comment)
      end
    end

    new_comment = reply ? reply : @comment

    if !params[:area] && (!current_user)
      new_comment.save if verify_recaptcha(:model => @comment, :message => I18n.t('recaptcha.errors.verification_failed'))
    else
      new_comment.save
    end

    ::Configuration.documents_repository.save(@document) unless new_comment.errors.any?

    if new_comment.persisted?
      current_user.log_comment_added(new_comment)
    end

    respond_to do |format|
      format.js
      format.html { redirect_to document_path(@document) }
    end
  end

  def toggle
    authorize!(:toggle, @comment)

    @comment.toggle(current_user)

    respond_to do |format|
      format.js { render :nothing => true }
      format.html { redirect_to document_path(@document) }
    end
  end

  def report
    @report = @comment.reports.build(params[:comment_report])
    @report.user = current_user
    @report.save!
    redirect_to document_path(@document)
  end

  def vote_up
    vote(:up)
  end

  def vote_down
    vote(:down)
  end

  def flag
    @comment.flags = @comment.flags + 1
    unless @comment.mail_sent
      if @comment.flags == ::Configuration.comment_flags_notify_threshold
        @comment.mail_sent = true
        NotificationMailer.flagged_comment_warning(@comment).deliver
      end
    end
    @comment.save
    respond_to do |format|
      format.js { render :json => @comment }
      format.html { redirect_to document_path(@document) }
    end
  end

  def flag_reason
    @comment.reports.create!(user: current_user, body: params[:note])
    render nothing: true
  end

  def recent
    @comments = Comment.chronologically.limit(3).offset(params[:offset].to_i)
    @next_offset = params[:offset].to_i + 3
  end

  private

  def vote(up_or_down)
    render :status => :unauthorized, :nothing => true and return unless current_user
    render :status => :forbidden, :nothing => true and return if current_user.already_voted_for?(@comment, up_or_down)

    current_user.vote_for(@comment, up_or_down)

    respond_to do |format|
      format.js { render :json => @comment }
      format.html { redirect_to document_path(@document) }
    end
  end

  def find_document
    @document = Document.find(params[:document_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def gravatar_url(user)
    if user.try(:email)
      "http://www.gravatar.com/avatar.php?gravatar_id=#{Digest::MD5::hexdigest(user.email)}"
    else
      asset_path "avatar.png"
    end
  end

  def link_to_comment(name, comment)
    link_to name, document_path(comment.document, anchor: dom_id(comment))
  end
end

app/views/comments/_comment.html.erb
<%= content_tag :div, :id => dom_id(comment) do %>
  <div class="comment-box comment-top">
    <%= content_tag :a, :name => dom_id(comment) do %>
      <div class="avatar">
        <%= image_tag gravatar_url(comment.user), :size => '60x60', :alt => comment.author_label %>
      </div>
    <% end %>
    <div class="comment">
      <p class="date"><%= comment.author_label %>, <%= time_ago_in_words(comment.created_at) %></p>
      <div class="text">
        <% if comment.censored? %>
            <% if can?(:toggle, comment) %>
              <p><em>Komentár bol odstránený <% if comment.censored_by %>moderátorom <%= comment.censored_by.name %><% else %>moderátorom<% end %>.</em></p>
              <%= simple_format(comment.comment) %>
            <% else %>
              <p><em>Komentár bol odstránený moderátorom.</em></p>
            <% end %>
        <% else %>
          <%= simple_format(comment.comment) %>
        <% end %>
      </div>
      <%= link_to '▲', vote_up_document_comment_path(@document, comment), :class => [:vote_up, :norm] %>
      <span class="current_votes"><%= comment.votes %></span>
      <%= link_to '▼', vote_down_document_comment_path(@document, comment), :class => :vote_down %>
      <a href="#" class="reply comment-menu" data-reply-to="<%= comment.id %>">Odpovedať</a>
      <% if comment.related_to_document_area? %>
        <%= link_to 'Zobraziť anotáciu v zmluve', comment_anchor(comment), :class => 'show_in_contract comment-menu' %>
      <% end %>
      <% if can?(:toggle, comment) %>
          <% if comment.censored? %>
              <%= link_to 'Povoliť zobrazenie komentára', toggle_document_comment_path(@document, comment), :method => :post, :class => 'comment-menu', 'data-confirm' => 'Naozaj chcete opať povoliť tento komentár?' %>
          <% else %>
            <%= link_to 'Skryť komentár', toggle_document_comment_path(@document, comment), :method => :post, :class => 'comment-menu', 'data-confirm' => 'Naozaj chcete skryť tento komentár?' %>
          <% end %>
      <% end %>
      <%= link_to 'Trvalý odkaz', document_path(@document, :anchor => "comment_#{comment.id}"), :class => 'comment-menu' %>
      <%= link_to 'Upozorniť na nevhodný komentár', flag_document_comment_path(@document, comment), 'data-reason-url' => flag_reason_document_comment_path(@document, comment), :method => :post, :class => 'comment-menu flag' %>
      <div class="messages"></div>
    </div>
    <div class="clear"></div>
  </div>
  <%= render :partial => 'comments/reply', :collection => comment.replies, :as => :comment %>
<% end %>

app/views/comments/_errors.html.erb
<ul class="errors">
  <% @comment.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end -%>
</ul>

app/views/comments/_reply.html.erb
<%= content_tag :div, :id => dom_id(comment) do %>
  <div class="comment-box subcomment comment-top">
    <%= content_tag :a, :name => dom_id(comment) do %>
    <div class="avatar"> 
      <%= image_tag gravatar_url(comment.user), :size => '60x60', :alt => comment.author_label %>
    </div>
    <% end %>
    <div class="comment">
      <p class="date"><%= comment.author_label %>, <%= time_ago_in_words(comment.created_at) %></p>
      <div class="text">
        <% if comment.censored? %>
            <% if can?(:toggle, comment) %>
                <p><em>Komentár bol odstránený <% if comment.censored_by %>moderátorom <%= comment.censored_by.name %><% else %>moderátorom<% end %>.</em></p>
                <%= simple_format(comment.comment) %>
            <% else %>
                <p><em>Komentár bol odstránený moderátorom.</em></p>
            <% end %>
        <% else %>
            <%= simple_format(comment.comment) %>
        <% end %>
      </div>
      <%= link_to '▲', vote_up_document_comment_path(@document, comment), :class => [:vote_up, :norm] %>
      <span class="current_votes"><%= comment.votes %></span>
      <%= link_to '▼', vote_down_document_comment_path(@document, comment), :class => :vote_down %>
      <% if can?(:toggle, comment) %>
          <% if comment.censored? %>
              <%= link_to 'Povoliť zobrazenie komentára', toggle_document_comment_path(@document, comment), :method => :post, :class => 'comment-menu', 'data-confirm' => 'Naozaj chcete opať povoliť tento komentár?' %>
          <% else %>
              <%= link_to 'Skryť komentár', toggle_document_comment_path(@document, comment), :method => :post, :class => 'comment-menu', 'data-confirm' => 'Naozaj chcete skryť tento komentár?' %>
          <% end %>
      <% end %>
      <%= link_to 'Trvalý odkaz', document_path(@document, :anchor => "comment_#{comment.id}"), :class => 'comment-menu' %>
      <%= link_to 'Upozorniť na nevhodný komentár', flag_document_comment_path(@document, comment), 'data-reason-url' => flag_reason_document_comment_path(@document, comment), :method => :post, :class => 'comment-menu flag' %>
      <div class="messages"></div>
    </div>
    <div class="clear"></div>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
  { "errors": "<%= escape_javascript(render 'errors') %>" }
<% else %>
  {"template": "<%= escape_javascript(render @comment) %>"}
<% end %>

app/views/comments/recent.js.erb
$('#tab_recent_comments .contract').last().after("<%= escape_javascript(render partial: 'documents/recent_comments', object: @comments, as: :comments) %>");
$('#tab_recent_comments .other-contracts a').first().replaceWith("<%= escape_javascript(link_to 'Ukáž ďalšie zmluvy'.html_safe, recent_comments_path(offset: @next_offset), remote: true) %>");