config/routes.rb
Crowdcloud::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resource :dashboard, controller: :dashboard do
    post :filter
  end

  namespace :admin do
    resources :comments do
      resources :reports
    end
    resources :spaceship_settings
    resources :heuristics
    resources :users do
      member do
        post :ban
        post :unban
        get :ban_ip
        post :ban_ip
        post :unban_ip
      end
    end
  end

  resource :comments do
    get :recent, on: :collection
  end

  resources :documents do
    get :search, :on => :collection
    post :quickfacet, :on => :collection
    post :toggle_visibility, :on => :collection
    post :watch, :on => :member
    post :unwatch, :on => :member
    resources :comments do
      member do
        post :vote_up
        post :vote_down
        post :flag
        post :flag_reason
        put :report
        post :toggle
      end
    end
    resources :questions
  end

  root :to => 'documents#index'

  match ':slug', :via => :get, :to => 'static_pages#show', :as => 'static_page'
  match ':slug', :via => :put, :to => 'static_pages#update', :as => 'static_page'

end

app/models/crz/document.rb
require_association 'crz/contract'
require_association 'crz/appendix'

class Crz::Document < Contract
  has_one :crz_document_detail, :class_name => 'Crz::DocumentDetail'

  delegate :crz_id, :crz_id=, :identifier, :identifier=, :department, :department=,
           :total_amount, :total_amount=, :contracted_amount, :contracted_amount=,
           :customer, :customer=, :supplier, :supplier=, :supplier_ico, :supplier_ico=, :note, :note=,
           :published_on, :published_on=, :effective_from, :effective_from=, :expires_on, :expires_on=,
           :emitter, :emitter=, :contract_crz_id, :contract_crz_id=, :status, :status=, :regis_supplier,
           :to => :lazy_detail

  def original_url
    "http://www.crz.gov.sk/index.php?ID=#{crz_id}&l=sk"
  end

  def self.find_all_by_crz_id(crz_ids)
    joins(:crz_document_detail).where(:crz_document_details => {:crz_id => crz_ids})
  end

  def lazy_detail
    @cached_detail ||= crz_document_detail || build_crz_document_detail
  end

  def source
    "www.crz.gov.sk"
  end
end

app/models/document.rb
require_association 'crz/document'
require_association 'egovsk/document'


class Document < ActiveRecord::Base
  has_and_belongs_to_many :matching_heuristics, :class_name => 'Heuristic', :uniq => true # do not allow heuristics duplication
  has_many :comments, :order => 'votes DESC, created_at DESC', :include => [:user, { :replies => [:user] }], :conditions => 'parent_id IS NULL'
  has_many :comments_including_replies, :order => 'votes DESC, created_at DESC', :include => [:user, { :replies => [:user] }], :class_name => 'Comment'
  has_many :question_answers

  has_many :watchlists
  has_many :watchers, through: :watchlists, class_name: 'User', source: :user
  has_many :document_openings

  include Document::Indexable
  include Document::NormalizedPoints
  include Document::NiceUrl

  def points
    matching_heuristics.reduce(0) { |sum, heuristic| sum + heuristic.on(self).points }
  end

  def comments_count
    comments_including_replies.count # TODO counter_cache?
  end

  def watcher_ids
    watchers.collect(&:id)
  end

  def opener_ids
    document_openings.collect(&:user_id)
  end
end

app/models/document/archivable.rb
module Document::Archivable
  extend ActiveSupport::Concern

  def path_to_hardcopy(type, options = {})
    directory = get_path(File.dirname(archive_path), options[:relative] || false)
    filename = File.basename(archive_path)

    base_path = File.join(directory, filename)

    case type
      when :as_is then base_path
      when :directory then directory
      when :original then "#{base_path}.pdf"
      when :text  then "#{base_path}-text.pdf"
      else raise "Hardcopy type '#{type}' is not available"
    end
  end

  private
  def get_path(path, relative = false)
    path_chunks = path.split('/')
    output = []
    path_chunks.each do |chunk|
      numbers = chunk.scan(/[0-9]{3,}/).collect do |part|
        part.to_i / 1000 * 1000
      end
      output += numbers if numbers.any?
      output << chunk
    end
    if relative
      "/documents/#{output.join('/')}"
    else
      "#{Rails.root}/public/documents/#{output.join('/')}"
    end
  end
end

app/models/document/nice_url.rb
module Document::NiceUrl
  def to_param
    "#{id}-#{customer.parameterize}-#{supplier.parameterize}-#{name.mb_chars[0..20].parameterize}"
  end
end

app/models/document/normalized_points.rb
module Document::NormalizedPoints
  include Normalization

  def normalized_points
    normalize_points(points, Configuration.normalize_points_to)
  end

  def denormalized_points
    denormalize_points(points, Configuration.normalize_points_to)
  end
end

app/models/egovsk/document.rb
class Egovsk::Document < Contract
  #TODO: try moving this to superclass
  has_many :attachments, :autosave => true
  has_one :egovsk_document_detail, :class_name => 'Egovsk::DocumentDetail', :autosave => true

  delegate :egovsk_id, :egovsk_id=,                        #"odkaz na detail"
           :total_amount, :total_amount=,                 #"cena"
           :customer_id, :customer_id=,                   #place_id in zmluvy.egov.sk
           :customer, :customer=,
           :founder, :founder=,
           :supplier, :supplier=,                         #"partner názov"
           :supplier_ico, :supplier_ico=,                 #"partner IČO"
           :note, :note=,                                 #"poznámka"
           :signed_on, :signed_on=,                       #"dátum podpisu"
           :published_on, :published_on=,                 #"dátum zverejnenia"
           :effective_from, :effective_from=,             #"dátum účinnosti"
           :valid_from, :valid_from=,                     #"platnosť od"
           :expires_on, :expires_on=,                     #"platnosť do"
           :contract_number, :contract_number=,           #"číslo zmluvy"
           :root_contract_number, :root_contract_number=, #"číslo pôvodnej zmluvy" (len appendix)
           :contract_type, :contract_type=,               #"druh zmluvy"
           :periodicity, :periodicity=,                   #"periodicita"
           :regis_supplier,
           :to => :lazy_detail

  attr_accessible :egovsk_attachment_type, :egovsk_doc_id, :egovsk_doc2_id, :name, :number,
                  :supplier

  def original_url
    "http://zmluvy.egov.sk/Egov/detail/id:#{egovsk_id}"
  end

  def self.find_all_by_egovsk_id(egovsk_ids)
    includes(:egovsk_document_detail).where(:egovsk_document_details => {:egovsk_id => egovsk_ids})
  end

  def lazy_detail
    @cached_detail ||= egovsk_document_detail || build_egovsk_document_detail
  end

  def source
    "zmluvy.egov.sk"
  end
end

require_association 'egovsk/contract'
require_association 'egovsk/appendix'

app/controllers/documents_controller.rb
# encoding: utf-8
class DocumentsController < ApplicationController
  before_filter :set_body_class
  caches_action :index, :layout => false, :expires_in => 10.minutes

  after_filter :log_document_opened, only: :show

  def index
    @statistics = documents_repository.statistics
    @most_recent = documents_repository.most_recent(SpaceshipSetting.find_by_identifier("recent_min_points").denormalized_value, SpaceshipSetting.find_by_identifier("recent_days").denormalized_value)
    @most_commented = documents_repository.most_commented
    @recent_comments = Comment.chronologically.limit(3).includes({ :document => :matching_heuristics }, :user)
    @query_facet = factic.quickfacet("q", params) # TODO get rid of this
  end

  def search
    session[:last_search] = params
    @title = "Vyhľadávanie"
    @query = params[:q] if params[:q].present?
    @visible_facet_names = [
        :customer, :supplier, :total_amount, :department, :comments_count, :published_on, :expires_on, :supplier_age, :appendixes_count,
        :supplier_nace, :source, :attachments_count, :total_pages_count, :legal_form, :ownership_category, :scope
    ]
    unless session[:hidden_facets]
      session[:hidden_facets] = [:attachments_count, :total_pages_count, :legal_form, :ownership_category]
    end

    @collapsed_facet_names = session[:hidden_facets]
    @sort_fields = [["Celkovej sumy", :total_amount], ["Dátumu zverejnenia", :published_on], ["Počtu komentárov", :comments_count]]
    params[:sort] ||= :total_amount
    params[:sort_order] ||= "desc"
    @results, @pages = search_documents(params) # TODO move pages search into repository?
    @restrictions_params = factic.extract_facets_params(params)
    @heuristic = Heuristic.find_or_initialize_by_search_parameters(@restrictions_params)
    @watched_documents = current_user.select_watched_documents(@results.hits) if current_user
  end

  def quickfacet
    # TODO visible facets only
    @facet_name = params[:facet]
    @facet = factic.quickfacet(@facet_name, params)
  end

  def show
    @last_search_params = session[:last_search].nil? ? {:action => :search} : {:action => :search}.reverse_merge(session[:last_search])
    @query = params[:q] if params[:q].present?
    @document = Document.find(params[:id])
    @attachments = @document.attachments.includes(:pages => :comments)
    @title = @document.title
    @matching_pages = @query ? pages_repository.search(@query, @document.id) : []

    @questions = @document.appendix? ? Question.for_appendix : Question.for_contract
    @visible_questions, @hidden_questions = @questions.partition(&:always_shown?)
    @watched_documents = current_user.select_watched_documents([@document]) if current_user
    if(current_or_guest_user.guest)
      @user_answers = QuestionAnswer.where(:document_id => @document.id, :guest_user_id => current_or_guest_user.id, :question_id => @questions.collect(&:id)).includes(:question_choice).group_by(&:question_choice)
    else
      @user_answers = QuestionAnswer.where(:document_id => @document.id, :user_id => current_or_guest_user.id, :question_id => @questions.collect(&:id)).includes(:question_choice).group_by(&:question_choice)
    end
  end

  def toggle_visibility
    if params[:to] == "collapsed"
      session[:hidden_facets] << params[:name].to_sym
    else
      session[:hidden_facets].delete(params[:name].to_sym)
    end
    render :nothing => true, :status => 200
  end

  def watch
    @document = Document.find(params[:id])
    current_user.watch(@document, params[:notice])
    render :nothing => true, :status => 200
  end

  def unwatch
    @document = Document.find(params[:id])
    current_user.unwatch(@document)
    render :nothing => true, :status => 200
  end

  private
  def search_documents(params)
    results = factic.search(params)
    doc_ids = results.hits.collect(&:id)
    pages_by_document_id = {}
    if params[:q].present? && doc_ids.any?
      pages_repository.search(params[:q], doc_ids).hits.each do |hit|
        pages_by_document_id[hit.attachment.document_id] ||= []
        pages_by_document_id[hit.attachment.document_id] << hit
      end
    end
    [results, pages_by_document_id]
  end

  def log_document_opened
    current_user.log_document_opened(@document) if current_user
  end

  def set_body_class
    @body_class = "detail" unless action_name == "index"
  end
end

app/helpers/documents_helper.rb
# encoding: utf-8
module DocumentsHelper
  def link_to_document(name, document)
    link_to name, document_path(document)
  end

  def format_unixtimestamp_to_month(timestamp)
    Time.at(timestamp / 1000).strftime("%m. %Y")
  end

  def document_discussion_path(document, options = {})
    document_path(document, options.merge(:anchor => 'diskusia'))
  end

  def document_page_anchor(page)
    "document/#{page.attachment.number}/page/#{page.number}"
  end

  def comment_anchor(comment)
    "document/#{comment.page.attachment.number}/page/#{comment.page.number}/comment/#{comment.id}"
  end

  def document_comment_anchor(document, comment)
    document_path(document, :anchor => dom_id(comment.id))
  end

  def t_page_count(count)
    t(:pages, :count => count.to_i)
  end

  def range_to_page_counts(range)
    return "menej ako #{t_page_count(range.end)}".html_safe if range.begin == -Infinity
    return "viac ako #{t_page_count(range.begin)}".html_safe if range.end == Infinity
    "#{range.begin.to_i} až #{t_page_count(range.end)}".html_safe
  end

  def range_to_points(range)
    human_numeric_range(range, :points)
  end

  def human_numeric_range(range, translator)
    return "menej ako #{t(translator, :count => range.end.to_i)}".html_safe if range.begin == -Infinity
    return "viac ako #{t(translator, :count => range.begin.to_i)}".html_safe if range.end == Infinity
    "#{range.begin.to_i} až #{t(translator, :count => range.end.to_i)}".html_safe
  end

  def range_to_datespan(range)
    from, to = range.begin, range.end
    if from.year == to.year
      if from.month == to.month
        if from == from.beginning_of_month && to == to.end_of_month
          return "#{l(from, :format => "%B %Y")}"
        end
      end

      if from == from.beginning_of_year && to == to.end_of_year
        return from.year
      end
      "#{l(from)} až #{l(range.end)}"
    else
      return "skôr ako #{to.year}" if from == Factic::RangeFacet::Converters::Date.lower_bound
      return "neskôr ako #{from.year}" if to == Factic::RangeFacet::Converters::Date.upper_bound
      "#{from.year} - #{to.year}"
    end
  end

  def humanize_duration(duration_in_days)
    years, rest = duration_in_days.divmod 365
    months, days = rest.divmod 30

    duration = []
    duration << t(:years, :count => years) if years > 0
    duration << t(:months, :count => months) if months > 0
    duration << t(:days, :count => days) if days > 0
    duration.join(' ')
  end

  def heuristics_from_hit(hit)
    result = ""
    hit.matching_heuristics.each do |heuristic|
      result << link_to(heuristic.name, search_documents_path(ActiveSupport::JSON.decode(heuristic.serialized_search_parameters).with_indifferent_access), :class => 'heuristic_label')
      result << "&nbsp;"
    end
    result
  end

  def shorten_department(department)
    department.gsub('Ministerstvo', 'Min.')
  end
end

app/views/documents/_document.html.erb
<table class='contract <%= "first" if document_counter == 0 %>'>
  <tbody>
    <tr class="space">
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="table-box-left">Názov</td>
      <td class="value contract-name"><%= link_to document.name, document_path(document) %></td>
    </tr>
    <tr>
      <td class="table-box-left">Obstarávateľ</td>
      <td class="value"><%= document.customer %></td>
    </tr>
    <tr>
      <td class="table-box-left">Dodávateľ</td>
      <td class="value"><%= document.supplier %></td>
    </tr>
    <tr>
      <td class="table-box-left">Cena</td>
      <td class="value"><span class="price"><%= number_to_euro(document.total_amount) || 'neznáma' %></span></td>
    </tr>
    <% if document.send("matching_heuristics").any? %>
      <tr class="labels">
        <td class="table-box-left">Zmluva spĺňa kritériá</td>
        <td class="value"><%= heuristics_from_hit(document).html_safe %></td>
      </tr>
    <% end %>
    <% if document.comments_count > 0 %>
      <tr>
        <td></td>
        <td><div class="comments_count"><%= link_to t(:comments, :count => document.comments_count), document_discussion_path(document) %></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/_empty_search_results.html.erb
<div id="top" class="glow empty">
  <div class="top-left" id="facets" data-url=<%= url_for(toggle_visibility_documents_path) %>>
    <h1>Naposledy hľadané</h1>
    <ul>
      <li><%= link_to 'Ministerstvo zahraničných vecí', search_documents_path(:q => 'Ministerstvo zahraničných vecí') %></li>
      <li><%= link_to 'Ministerstvo školstva', search_documents_path(:q => 'Ministerstvo školstva') %></li>
      <li><%= link_to 'Ministerstvo kultúry', search_documents_path(:q => 'Ministerstvo kultúry') %></li>
      <li><%= link_to 'Iveta Radičová', search_documents_path(:q => 'Iveta Radičová') %></li>
      <li><%= link_to 'Róbert Fico', search_documents_path(:q => 'Róbert Fico') %></li>
    </ul>
  </div>
  <div class="top-right">
    <p>Nenašli sme žiadne výsledky.</p>
    <p>Skúste upraviť kritériá vyhľadávania.</p>
  </div>
  <div class="clear"></div>
</div>

app/views/documents/_page_navigation.html.erb
<div class="pages _dv_page_nav">
  <a href="" class="up _dv_prev_page" title="Predchádzajúca strana">&uarr;</a>
  <input type="text" class="_dv_current_page" size="2" /> <span>/</span> <span class="_dv_total_pages"></span>
  <a href="" class="down _dv_next_page" title="Nasledujúca strana">&darr;</a>
</div>

app/views/documents/_pie_chart.html.erb
<script>
  var chart;
  $(document).ready(function() {
    var options = {
      chart: {
        renderTo: 'pie_chart_container',
        backgroundColor: '#eef2f6',
        plotBackgroundColor: '#eef2f6',
        width: 360,
        plotBorderWidth: null,
        plotShadow: false,
        spacingTop: 0,
        spacingBottom: 0,
        spacingLeft: 0,
        spacingRight: 0,
        style: {
          marginLeft: '5px'
        },
        events: {
          load: function(event) {
            $.each(this.series[0].data, function() {
              var data_entry = this
              $("td[class=resort] a[title=\""+data_entry.name+"\"]").each(function(index) {
                $(this).siblings('span').attr("style", "font-size:8px;background-color:" + data_entry.color)
              });
            });
          }
        }

      },
      credits: {
        enabled: false
      },
      title: {
        text: null
      },
      tooltip: {
        formatter: function() {
          return '<b>' + this.point.name +'</b>: ' + Math.round(this.percentage) + ' %';
        }
      },
      plotOptions: {
        pie: {
          allowPointSelect: true,
          cursor: 'pointer',
          dataLabels: {
            enabled: false
          },
          showInLegend: false
        }
      },
      series: [{
        type: 'pie',
        name: 'Ministerstvá',
        data: []
      }]
    }

    <% total = @statistics.amounts_by_department.terms.inject(0) do |sum, n| %>
      <% sum + (n.total.to_i) %>
    <% end %>
    <% @statistics.amounts_by_department.terms.each do |department| %>
      options.series[0].data.push(["<%= truncate(shorten_department(department.term), :length => 40) %>" , <%= department.total * 100/(total) %>]);
    <% end %>
    chart = new Highcharts.Chart(options);
  });
</script>

app/views/documents/_question.html.erb
<div id="question_placeholder_<%= question.id %>" class="question-placeholder" data-url="<%= document_question_url(@document, question) %>"></div>

app/views/documents/_search_results.html.erb
<div id="top" class="glow">
  <div class="top-left" id="facets" data-url=<%= url_for(toggle_visibility_documents_path) %>>
    <% if @restrictions_params.any? %>
        <p class="reset">
          <%= link_to search_documents_path do %>
              <strong><span>&#10006;</span>Zmazať všetky obmedzenia</strong>
          <% end %>
        </p>
    <% end %>
    <ul>
      <% @visible_facet_names.each_with_index do |name, index| %>
          <% facet = @results.facets[name] %>
          <% next unless facet %>
          <% visibility = @collapsed_facet_names.include?(name) ? "collapsed ":"open " %>
          <%= content_tag :li, :class => "facet #{visibility.to_s+name.to_s}#{' first' if index == 0}", "data-name" => name.to_s do %>
            <%= content_tag :a, t("facets.#{name}"), :class => :title, :href => "#" %>
            <%= render :partial => "facets/#{name}_facet", :object => facet, :as => :facet %>
          <% end %>
      <% end %>
    </ul>
  </div>
  <div class="top-right">
    <div class="select-panel">
      <% statistics = @results.facets[:total_amount_stats] %>
      <% unless @heuristic.new_record? %>
        <div class="heuristic">
          Kategória: <em><%= @heuristic.name %></em>
        </div>
      <% end %>
      <p>Spolu <span class="strong"><%= number_to_euro(statistics.total) %></span>
        v <strong><%= t(:in_n_contracts, :count => number_with_delimiter(@results.hits.total)) %></strong>.</p>

      <div class="select-right">
        <div class="select-right-left">Zoradiť podľa
          <%= form_tag search_documents_path, :method => :get, :class => "jqtransform" do %>
              <% @results.search_params.each_pair do |name, value| %>
                  <% unless ["controller", "action", "sort", "sort_order", "utf8"].include? name %>
                      <% if value.is_a?(Array) %>
                          <% value.each do |entry| %>
                            <%= hidden_field_tag "#{name}[]", entry %>
                          <% end %>
                      <% else %>
                          <%= hidden_field_tag name, value %>
                      <% end %>
                  <% end %>
              <% end %>
              <p><%= select_tag :sort, options_for_select(@sort_fields, @results.search_params[:sort]), :class => :sort %></p>
          <% end %>
        </div>
        <% if params[:sort_order] == "desc" %>
            <div class="nav"><a href="#" class="next active"></a> <a href="#" class="prew"></a></div>
        <% else %>
            <div class="nav"><a href="#" class="next"></a> <a href="#" class="prew active"></a></div>
        <% end %>

      </div>
      <div class="clear"></div>
      <% if can? :read, Heuristic %>
          <p><%= link_to @heuristic.new_record? ? "Vytvoriť heuristiku" : "Upraviť heuristiku", "#", 'data-toggle-id' => :heuristic_form, 'data-focus-id' => :heuristic_name %></p>
      <% end %>
      <div style="display: none" id="heuristic_form">
        <%= form_for [:admin, @heuristic] do |f| %>
            <%= f.hidden_field :serialized_search_parameters %>
            <p><%= f.label :name, "Názov heuristiky" %>:<br><%= f.text_field :name %></p>

            <p><%= f.label :formula, "Počet bodov" %>:<br><%= f.text_field :formula, :size => 4 %></p>

            <p><%= f.label :explanation, "Vysvetlenie" %>:<br> <%= f.text_area :explanation, :rows => 5 %></p>

            <p><%= f.submit @heuristic.new_record? ? "Vytvoriť heuristiku" : "Upraviť heuristiku" %>
              <% if @heuristic.persisted? %>
                  alebo <%= link_to "Zmazať heuristiku", admin_heuristic_path(@heuristic), :method => :delete, :confirm => "Chcete naozaj zmazať túto heuristiku?" %>
              <% end %></p>
        <% end %>
      </div>
    </div>
    <div class="clear"></div>
        <div class="overview">
          <ol start="<%= @results.offset %>">
            <% @results.hits.each_with_index do |hit, index| %>
                <li class="<%= 'nobr' if index == @results.hits.length - 1 %>">
                  <div class="li-left">
                    <h2 class="title"><%= link_to hit.highlighted_name || "Dokument bez uvedeného názvu", document_path(hit, :q => @query) %></h2>

                    <div class="notice">
                      <p>
                        <strong>Obstarávateľ:</strong> <%== hit.highlighted_customer %></p>
                      <p>
                        <strong>Dodávateľ:</strong> <%== hit.highlighted_supplier %></p>
                      <p>
                        <strong>Dátum zverejnenia:</strong> <%= l(Date.strptime(hit.published_on, "%Y-%m-%d")) rescue "" %></p>
                      <% if hit.matching_heuristics && hit.matching_heuristics.any? %>
                        <p><strong>Zmluva spĺňa kritériá:</strong> <%= heuristics_from_hit(hit).html_safe %></p>
                      <% end %>
                    </div>
                  </div>
                  <div class="li-right">
                    <div class="price"><%= number_to_euro(hit.total_amount) || 'neznáma' %></div>
                    <div class="controls">
                      <%= render 'dashboard/watch', document: hit %>
                    </div>
                  </div>
                  <div class="clear"></div>
                  <% highlighted_pages = @pages[hit.id] %>
                  <% if highlighted_pages %>
                      <% highlighted_pages.each do |page| %>
                            <% page.highlights(:text).each do |highlight| %>
                                <p class="found"><%== highlight %></p>
                            <% end %>
                      <% end %>
                  <% end %>
                </li>
            <% end %>
          </ol>
        </div>
    <div class="paging-panel">
      <div>
        <%= @results.offset %> - <%= @results.offset + @results.hits.count - 1 %> z <%= t(:of_n_contracts, :count => number_with_delimiter(@results.hits.total)) %> (Nájdené za <%= number_with_delimiter(@results.took) %>ms)&nbsp;&nbsp;&mdash;&nbsp;&nbsp;<%= link_to 'RSS feed', search_documents_path(:rss, @results.search_params)  %>
      </div>
      <%= paginate @results %>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/documents/index.html.erb
<%= render 'pie_chart' %>
<div id="search_panel">
  <%= render :partial => "facets/q_facet", :object => @query_facet, :as => :facet %>
  <%= link_to "Rozšírené vyhľadávanie", search_documents_path %>
</div>
<div id="content">
  <p class="contracts">Za posledný mesiac boli zverejnené zmluvy v hodnote</p>
  <div class="top-banner">
    <% offset = @statistics.amounts_from_last_week.total.to_i.to_s.length % 3 %>
    <% @statistics.amounts_from_last_week.total.to_i.to_s.chars.each_with_index do |digit, index| %>
        <% if (index+1+3-offset) % 3 == 0 %>
            <span class="number third"><%= digit %></span>
        <% else %>
            <span class="number"><%= digit %></span>
        <% end %>
    <% end %>
    <span>&nbsp;€</span>
    </div>
    <p class="cta">
      <%= link_to 'Chcem ich ohodnotiť', search_documents_path, :title => 'Rozšírené vyhľadávanie', :class => 'button' %>
    </p>

  <div class="clear"></div>

  <ul id="tabs">
    <li>
       <%= link_to "Nové zaujímavé zmluvy", "#", :class => "active", 'data-tab-switch' => 'tab_most_recent' %>
    </li>
    <li>
       <%= link_to "Najdiskutovanejšie zmluvy", "#", 'data-tab-switch' => 'tab_most_commented' %>
    </li>
    <li>
       <%= link_to "Posledné komentáre", "#", 'data-tab-switch' => 'tab_recent_comments' %>
    </li>
  </ul>
  <div id="top-index" class="glow">
    <div class="top-left-index">
      <div id="tab_most_recent" class="tab">
        <%= render :partial => 'document', :collection => @most_recent.hits %>
        <div class="other-contracts">
          <%= link_to "Ukáž ďalšie zmluvy".html_safe, search_documents_path(:sort => :published_on) %>
        </div>
      </div>
      <div id="tab_most_commented" class="tab">
        <%= render :partial => 'document', :collection => @most_commented.hits %>
        <div class="other-contracts">
          <%= link_to "Ukáž ďalšie zmluvy".html_safe, search_documents_path(:sort => :comments_count) %>
        </div>
      </div>
      <div id="tab_recent_comments" class="tab">
        <%= render 'recent_comments', comments: @recent_comments %>
        <div class="other-contracts">
          <%= link_to "Ukáž ďalšie zmluvy".html_safe, recent_comments_path(offset: 3), remote: true %>
        </div>
      </div>
    </div>
    <div class="top-right-index">
      <%= render :partial => 'slider' %>
    </div>
    <div class="clear"></div>
  </div>

  <div class="contracts-footer">
    Máme pre vás <strong><%= number_with_delimiter(@statistics.all.count) %></strong> zmlúv v hodnote <strong><%= number_to_euro(@statistics.amounts.total) %></strong> a stále pribúdajú&hellip;
  </div>
</div>

app/views/documents/quickfacet.js.erb
$("#facets .<%= @facet_name %> .list").replaceWith("<%= escape_javascript(render :partial => "factic/searchable_terms_facet", :object => @facet, :as => :facet) %>");

app/views/documents/search.html.erb
<div id="search_panel">
  <% facet = @results.facets[:q] %>
  <%= render :partial => "facets/q_facet", :object => facet, :as => :facet %>
</div>
<div id="content">
  <ul id="tabs">
    <li class="active"><a href="#" class="list">Zoznam</a></li>
  </ul>
  <div class="top-for-bottombg">
    <% if @results.hits.any? %>
      <%= render :partial => 'search_results' %>
    <% else %>
      <%= render :partial => 'empty_search_results' %>
    <% end %>
  </div>
</div>