config/routes.rb
Crowdcloud::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users

  resource :dashboard, controller: :dashboard do
    post :filter
  end

  namespace :admin do
    resources :comments do
      resources :reports
    end
    resources :spaceship_settings
    resources :heuristics
    resources :users do
      member do
        post :ban
        post :unban
        get :ban_ip
        post :ban_ip
        post :unban_ip
      end
    end
  end

  resource :comments do
    get :recent, on: :collection
  end

  resources :documents do
    get :search, :on => :collection
    post :quickfacet, :on => :collection
    post :toggle_visibility, :on => :collection
    post :watch, :on => :member
    post :unwatch, :on => :member
    resources :comments do
      member do
        post :vote_up
        post :vote_down
        post :flag
        post :flag_reason
        put :report
        post :toggle
      end
    end
    resources :questions
  end

  root :to => 'documents#index'

  match ':slug', :via => :get, :to => 'static_pages#show', :as => 'static_page'
  match ':slug', :via => :put, :to => 'static_pages#update', :as => 'static_page'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me, :admin, :expert, :terms_of_service

  validates_presence_of :name
  validates_acceptance_of :terms_of_service

  has_many :comments
  has_many :question_answers
  has_many :votings
  has_many :watchlists

  has_many :watched_documents, through: :watchlists, class_name: 'Document', source: :document
  has_many :stream_events, class_name: 'Event', foreign_key: :for_user_id

  has_many :document_openings

  belongs_to :banned_ip, :foreign_key => :last_sign_in_ip, :primary_key => :ip

  scope :name_or_email_contains, lambda { |query| where(['LOWER(name) LIKE LOWER(?) OR LOWER(email) LIKE LOWER(?)', "%#{query}%", "%#{query}%"]) }

  after_create :log_user_registered

  def label
    name
  end

  def guest
    false
  end

  def already_voted_for?(comment, up_or_down)
    votings.find_by_comment_id(comment.id)
  end

  def vote_for(comment, up_or_down)
    comment.votings.create(:up_or_down => up_or_down, user: self)
    case up_or_down
      when :up then comment.update_attributes(:votes => comment.votes + 1)
      when :down then comment.update_attributes(:votes => comment.votes - 1)
    end
  end

  def self.find_for_authentication(conditions)
    super(conditions.merge(:banned => false))
  end

  def watch(document, notice)
    watched_document = watched_document(document)
    if watched_document
      watched_document.update_attributes(notice: notice)
    else
      watchlists.create(document: document, notice: notice)
      Configuration.documents_repository.save(document) # TODO update API
    end
  end

  def unwatch(document)
    watched_document(document).destroy
    Configuration.documents_repository.save(document) # TODO update API
  end

  def watched_document(document)
    watchlists.where(document_id: document.id).first
  end

  def watching?(document)
    watched_document(document)
  end

  def notice_for(document)
    watched_document(document).try(:notice)
  end

  def stream_filters
    {
        show_watching: stream_show_watching,
        show_my_comments: stream_show_my_comments,
        show_other_comments: stream_show_other_comments,
        show_openings: stream_show_openings,
        show_answers: stream_show_answers,
    }
  end

  def dashboard_events
    allowed_events = [UserRegisteredEvent]
    allowed_events += [WatchingStartedEvent, WatchingStoppedEvent] if stream_show_watching?
    allowed_events += [MyCommentEvent] if stream_show_my_comments?
    allowed_events += [OthersCommentEvent] if stream_show_other_comments?
    allowed_events += [DocumentOpenedEvent] if stream_show_openings?
    allowed_events += [QuestionAnswerEvent] if stream_show_answers?
    stream_events.where(type: allowed_events.collect(&:to_s)).order('updated_at DESC')
  end

  def select_watched_documents(documents)
    documents = watchlists.where(document_id: documents.collect(&:id))
    WatchedDocuments.new(documents)
  end

  # Events
  def log_document_opened(document)
    unless document_openings.where(document_id: document.id).exists?
      document_openings.create(document_id: document.id)
      Configuration.documents_repository.save(document) # TODO update API
    end

    return unless watched_documents.include?(document)
    recently_opened = DocumentOpenedEvent.where('updated_at >= ?', 30.minutes.ago).where(for_user_id: self.id, external_id: document.id).first
    if recently_opened
      recently_opened.touch
    else
      DocumentOpenedEvent.create!(for_user: self, external: document)
    end
  end

  def log_comment_added(comment)
    MyCommentEvent.create!(for_user: self, comment: comment)
    comment.document.watchers.each do |watcher|
      OthersCommentEvent.create!(for_user: watcher, comment: comment) if watcher != self
    end
  end

  def log_question_answered(question_answer)
    QuestionAnswerEvent.create!(for_user: self, external: question_answer)
  end

  def log_user_registered
    UserRegisteredEvent.create!(for_user: self, external: self)
  end

  class WatchedDocuments
    def initialize(watchlists)
      @notices = watchlists.inject({}) { |notices, watchlist| notices[watchlist.document_id] = watchlist.notice; notices }
    end

    def include?(document)
      @notices.include?(document.id)
    end

    def notice_for(document)
      @notices[document.id]
    end
  end
end

app/controllers/admin/users_controller.rb
# encoding: utf-8
class Admin::UsersController < AdminController
  authorize_resource

  def index
    @query = params[:q]
    @users = User.order('id ASC')
    @users = @users.name_or_email_contains(@query) unless @query.blank? # TODO replace with fulltext
    @users = @users.page(params[:page])
  end

  def update
    user = User.find(params[:id])
    user.update_attributes(params[:user])
    redirect_to admin_users_path, notice: "Zmena používateľa #{user.name} bola úspešná."
  end

  def ban
    if(request.post?)
      user = User.find(params[:id])
      user.banned = true
      user.save
      redirect_to admin_users_path
    end
  end

  def unban
    if(request.post?)
      user = User.find(params[:id])
      user.banned = false
      user.save
      redirect_to admin_users_path
    end
  end

  def ban_ip
    if(request.get?)
      user = User.find(params[:id])
      @users = User.select("name,email").where(:last_sign_in_ip => user.last_sign_in_ip)
      render :json => @users
    else
      user = User.find(params[:id])
      banned_ip = BannedIp.find_or_create_by_ip(user.last_sign_in_ip, :creator_id => current_user.id)
      render :json => banned_ip
    end
  end

  def unban_ip
    user = User.find(params[:id])
    user.banned_ip.try(:destroy)
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < AuthorizedController
  def show
    @body_class = "detail user"

    @user = User.find(params[:id])
    @recent_comments = @user.comments.order('comments.id DESC').limit(5)
    @recent_question_answers = @user.question_answers.select("document_id, MAX(created_at) AS created_at").group("document_id").order("MAX(created_at) DESC").limit(5)
    @watched_documents = @user.watched_documents
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<section>
  <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= link_to '&times;'.html_safe, '#', class: :close, data: {dismiss: :alert} %>
        <%= flash[:notice] %>
      </div>
  <% end %>
  <div class="row">
    <div class="span9">
      <h1>Používatelia</h1>
    </div>

    <div class="span3 searchbox">
      <%= form_tag admin_users_path, class: 'form-search', method: :get do %>
          <div class="input-append">
            <%= text_field_tag :q, @query, class: ['input-small', 'search-query'] %>
            <%= button_tag 'Hľadaj', class: :btn, name: nil %>
          </div>
      <% end %>
    </div>
  </div>
  <% if @users.length > 0 %>
      <table class="users table table-condensed">
        <thead>
        <tr>
          <th>Meno</th>
          <th>Email</th>
          <th>Admin?</th>
          <th>Expert?</th>
          <th>Vytvorený dňa</th>
          <th>Posledné prihlásenie</th>
          <th>Posledná IP adresa</th>
          <th class="actions">Akcie</th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <%= content_tag :tr, class: user.banned? ? :banned : nil do %>
                <td><%= link_to user.name, user %></td>
                <td><%= user.email %></td>
                <td>
                  <%= form_for [:admin, user] do |f| %>
                      <%= f.check_box :admin, :class => "user_admin" %>
                  <% end %>
                </td>
                <td>
                  <%= form_for [:admin, user] do |f| %>
                      <%= f.check_box :expert, :class => "user_expert" %>
                  <% end %>
                </td>
                <td class="date"><%= date_to_human(user.created_at) %></td>
                <td class="date"><%= date_to_human(user.last_sign_in_at) %></td>
                <% style = user.banned_ip.nil? ? nil : "style=text-decoration:line-through;" %>
                <td <%= style %>><%= user.last_sign_in_ip %></td>
                <td class="actions">
                  <% unless user.banned %>
                      <%= link_to 'ban účtu', ban_admin_user_path(user), :method => :post, :class => "btn btn-mini btn-danger", :confirm => "Naozaj chcete #{user.name} zablokovať?" %>
                  <% else %>
                      <%= link_to 'un-ban účtu', unban_admin_user_path(user), :method => :post, :class => "btn btn-mini btn-danger", :confirm => "Naozaj chcete #{user.name} odblokovať?" %>
                  <% end %>

                  <% if user.banned_ip.nil? %>
                      <%= link_to 'ban IP', ban_ip_admin_user_path(user), :method => :post, :class => "btn btn-mini btn-danger" %>
                  <% else %>
                      <%= link_to 'un-ban IP', unban_ip_admin_user_path(user), :method => :post, :class => "btn btn-mini btn-danger", :confirm => "Naozaj IP adresu chcete #{user.last_sign_in_ip} odblokovať?" %>
                  <% end %>
                </td>
            <% end %>
        <% end %>
        </tbody>
      </table>
      <%= paginate @users, theme: 'twitter-bootstrap' %>
  <% else %>
      <p>Nenašli sa žiadni používatelia.</p>
  <% end %>
</section>